project:
  title: "Monte Carlo"
  type: website
  output-dir: ./docs

website:
  title: "Monte Carlo"
  navbar:
    left:
      - href: info.qmd
        text: Info
    right:
      - href: ./
        text: Pl
      - href: ./en
        text: En
        
lang: pl        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



