project:
  title: "Monte Carlo"
  type: website
  output-dir: ./docs/en

website:
  title: "Monte Carlo"
  navbar:
    left:
      - href: about.qmd
        text: About
    right:
      - href: ../
        text: Pl
      - href: ./
        text: En
        
lang: en        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



